### ISSUE TITLE
View factors between sky and surfaces 

### ISSUE THREAD

**Issue by ArhurP** [LBNL-ETA/frads#58]
Dear all, 

In the context of outdoor long wave radiation, it is necessary to calculate  view factors between  surfaces and also between the surface and the sky. 

Using the **surfaces_view_factor function**, is there a way to determine the view factors between, for example, the sky and the ground and a given geometry and in between ground and geometry?

 The sky is discretized following the Reinhart sky model for a usage with daylight coefficient for shortwave radiation with the following skyglow.rad file: 

#@rfluxmtx u=+Y h=u
void glow groundglow
0
0
4 1 1 1 0

groundglow source ground
0
0
4 0 0 -1 180

#@rfluxmtx u=+Y h=r1
void glow skyglow
0
0
4 1 1 1 0

skyglow source skydome
0
0
4 0 0 1 180

Sincerely, 
Arthur

**Comment by taoning** [comment]
The `surface_view_factor` function is meant for view factor calculation in context of complex geometry.  When involving sky as receiver, you can simply use `rfluxmtx`, You would need to use `h=u` for the sky source because discretization doesn't help us here, and ground would need to be `polygon` and not `source`.  The same goes for surface to sky view factor. Hope this helps.

**Comment by ArhurP** [comment]
Dear Taoning, 

Thank you for your response that is super clear. The ground is in fact a series of polygons made up of triangles to make it compatible with surface_view_factor between a given set of primitives of surfaces with the same modifier and the ground.rad. 

Does it make sense to keep the ground as seen previously in the skyglow.rad for a closing sphere between the sky and ground at "infinite distance" with the finite dimensions of the ground.rad ?  

Sincerely, 
Arthur

**Comment by taoning** [comment]
I think you can do `rfluxmtx sender.rad skyglow.rad` for you view factor from "surface" to "source". You would put a single polygon in the `sender.rad`.  If this polygon is ground, your first value from your result would be zero, since ground is not "seeing" ground.  Pay attention to the polygon surface normal, your ground polygon should point downward.
